Update CocoaLumberJack integration to define ddLogLevel as a const int rather than int
[CocoaLumberJack docs](https://github.com/robbiehanson/CocoaLumberjack/wiki/XcodeTricks) suggest setting ddLogLevel as below

```objective-c
#ifdef DEBUG
  static const int ddLogLevel = LOG_LEVEL_VERBOSE;
#else
  static const int ddLogLevel = LOG_LEVEL_WARN;
#endif
```

Which causes an issue in MagicalRecord.h of 

```
MagicalRecord/MagicalRecord.h:26:20: Redefinition of 'ddLogLevel' with a different type: 'int' vs 'const int'
```

This change fixes that.